---
- hosts: localhost
  connection: local
  name: "Shell setup"

  vars:
    oh_my_zsh_plugins:
      - git
      - fzf
      - z
      - zsh-syntax-highlighting
      - zsh-interactive-cd
      - zsh-autosuggestions
      - docker
      - docker-compose

    p10k_prompt_style: "lean"
    p10k_prompt_spacing: sparse
    p10k_prompt_flow: fluent
    p10k_transient_prompt: "yes"
    zsh_plugin: ohmyzsh

  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ ansible_user_id }}"
    - role: diodonfrost.p10k

  tasks:
    - name: Add syntax highlighting plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
        version: master

    - name: Add autosuggestions plugin
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        version: master

    - name: Download fzf
      ansible.builtin.git:
        repo: https://github.com/junegunn/fzf.git
        dest: "{{ ansible_env.HOME }}/.fzf"
        depth: 1
        version: master

    - name: Install fzf
      ansible.builtin.shell: "{{ ansible_env.HOME }}/.fzf/install --all"

    - name: Add .local/bin to .zshrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        insertbefore: '\# BEGIN P10K CONFIG FILE ANSIBLE MANAGED BLOCK'
        line: export PATH="$HOME/.local/bin:$PATH"
