- name: "NPM setup"
  hosts: localhost

  tags:
    - node

  block:
    - name: Install nvm
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

    - name: Install Node.js
      shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install node"
      args:
        executable: /bin/zsh

    # TODO CLEANUP THIS TO USE NPX (not working for some reason)
    - name: Install TL;DR
      shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh && npm install -g tldr"
      args:
        executable: /bin/bash
