- name: Setup ZSH
  become: true

  tags:
    - install
    - core

  block:
    # TODO Check if it works on MacOS
    - name: Install CLI tools through package manager
      ansible.builtin.package:
        name:
          - git
          - zsh
          - neovim
          - exa
          - bat
          - zoxide
          - ripgrep
        state: present

    # This does not work in Docker but works if running locally
    - name: Change default shell
      shell: chsh -s `which zsh`

    # Not on apt yet unfortunately
    - name: Install Starship
      shell: curl -sS https://starship.rs/install.sh | sh -s -- -y

    - name: Checkout fzf
      ansible.builtin.git:
        repo: "https://github.com/junegunn/fzf.git"
        dest: ~/.fzf

    - name: Install fzf
      shell: ~/.fzf/install --key-bindings --completion --no-update-rc

    # TODO Zellij not on APT + no simple script
    # - name: Install zellij
    #   shell: curl -sS https://zellij.dev/launch | sh

    # Not working on Ubuntu ARM64
    - name: Install atuin
      shell: curl -sS https://raw.githubusercontent.com/ellie/atuin/main/install.sh | bash
