- name: Setup ZSH
  become: true

  tags:
    - install
    - core

  block:
    - name: Install zsh
      apt:
        name: zsh
        state: present

    - name: Change shell
      shell: chsh -s `which zsh`

    - name: Install Starship
      shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
