---
- hosts: localhost
  connection: local 
  name: "Shell setup"

  vars:
    oh_my_zsh_plugins:
      - git
      - z
      - zsh-syntax-highlighting
      - zsh-interactive-cd
      - zsh-autosuggestions
      - docker
      - docker-compose
    p10k_prompt_spacing: sparse
    p10k_prompt_flow: fluent
    p10k_transient_prompt: "yes"
    zsh_plugin: ohmyzsh

  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ ansible_user_id }}"
    - role: diodonfrost.p10k

  tasks:
    - name:                       Add syntax highlighting plugin
      ansible.builtin.git:
        repo:                     https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest:                     "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
        version:                  master

    - name:                       Add autosuggestions plugin
      ansible.builtin.git:
        repo:                     https://github.com/zsh-users/zsh-autosuggestions 
        dest:                     "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        version:                  master

    - name:                       Add .local/bin to .zshrc
      ansible.builtin.lineinfile:
        path:                     "{{ ansible_env.HOME }}/.zshrc"
        insertbefore:             '\# BEGIN P10K CONFIG FILE ANSIBLE MANAGED BLOCK'
        line:                     export PATH="$HOME/.local/bin:$PATH"
